#!/usr/bin/python3

import requests, json
from pymongo import MongoClient
import pprint
from sys import argv

if __name__ == "__main__":

def aggregate_yelp(name, location):
    client_id = 'SQqV-EaSklWJV9089z-LRg'
    client_secret = 'QkIzkk76Lv3wOWKK8lSgU794edzjo96sKfFrDolT4c6hHWivZfoZU1WKDLof9WII'
    data = {'grant_type': 'client_credentials',
            'client_id': client_id,
            'client_secret': client_secret}
    token = requests.post('https://api.yelp.com/oauth2/token', data=data)
    access_token = token.json()['access_token']
    url = 'https://api.yelp.com/v3/businesses/search'
    headers = {'Authorization': 'bearer %s' % access_token}
    params = {'term': 'Pizzeria Delfina' name,
                'location': 'Burlingame Avenue, Burlingame, California, 94010, United States of America' location,
                'limit': 1
              }

    resp = requests.get(url=url, params=params, headers=headers)
    business_details = resp.json()['businesses']
    # Getting id to possibly pass into new endpoint: business/{id}
    for item in business_details:
        business_id = item.get('id')
        phone_num = item.get('phone')
        price = item.get('price')
        rating = item.get('rating')
        reviews_count = item.get('review_count')
        image = item.get('image_url')
        coordinates = item.get('coordinates')
    print("id: ", business_id, ", phone:", phone_num, ", price: ", price, ", rating: ", rating, ", image: ", image, ", reviews: ", reviews_count, ", coord: ", coordinates)
